version: v3
services: 
  todo-api:
    build: ./TodoApp/
    ports:
      - "8001:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - DO_MIGRATE=true
  cmd-app:
    build: ./CmdApp/
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - BACKEND_URL=http://todo-api:80
    depends_on: 
        - todo-api
